### ISSUE TITLE
Antialiasing issues

### ISSUE THREAD

**Issue by luckyclan** [styluslabs/nanovgXC#2]
I noticed a lot of aliased edges in VgerDemo...

![IMG_344AD2AF55DD-1](https://user-images.githubusercontent.com/31405913/153211015-86610ce7-68ed-44c8-bc75-c7b73be2fb8f.jpeg)

**Comment by pbsurf** [comment]
Are you referring to https://github.com/audulus/vger-demo ?  Modified to use nanovgXC?  If so, could you provide the code to reproduce or some more details: which nanovgXC backend - nanovg_sw or nanovg_gl and which platform/GPU (an iOS device?)

**Comment by luckyclan** [comment]
> Are you referring to https://github.com/audulus/vger-demo ? Modified to use nanovgXC? If so, could you provide the code to reproduce or some more details: which nanovgXC backend - nanovg_sw or nanovg_gl and which platform/GPU (an iOS device?)

Ups, sorry, i wanted to report that in vger repo...
