### ISSUE TITLE
vertex texture maping

### ISSUE THREAD

**Issue by mariuszmaximus** [styluslabs/nanovgXC#6]
Is possible draw vertex and map texture UV to vertex ? 

Like https://people.eecs.berkeley.edu/~ug/slide/pipeline/assignments/as9/texture.gif

**Comment by pbsurf** [comment]
To draw an image, load the image with one of the `nvgCreateImage()` functions, create a paint object for the image using `nvgImagePattern()`, set the paint object as the current fill with `nvgFillPaint()`, then draw a path to be filled with image, e.g., using `nvgRect()`
