### ISSUE TITLE
Should these lines be guarded in `xjoin == NVG_MITTER` according to the comment

### ISSUE THREAD

**Issue by mhfan** [styluslabs/nanovgXC#9]
https://github.com/styluslabs/nanovgXC/blob/c5ea846d7f23b663793ca0aa6a42da28a60de8f0/src/nanovg.c#L1579

`nvg__segment(dst++, lx, ly, l01x, l01y);  // first segment (and only for miter join)`

https://github.com/styluslabs/nanovgXC/blob/c5ea846d7f23b663793ca0aa6a42da28a60de8f0/src/nanovg.c#L1598

`nvg__segment(--rdst, r01x, r01y, rx, ry);  // first segment (and only for miter join)`

**Comment by pbsurf** [comment]
Sorry, comment is poorly worded - intended to mean that this is the "first and only segment" for miter join case whereas other cases include additional segments
